[project]
name = "sports-utils"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "balldontlie>=0.1.6",
    "dotenv>=0.9.9",
    "pydantic>=2.12.3",
    "rich>=14.2.0",
    "typer>=0.20.0",
]
